### ISSUE TITLE
Input node with more advanced features.

### ISSUE THREAD

**Issue by jeroenhendricksen** [pdmangel/node-red-contrib-openhab2#25]
I’m using your plugin for quite some time now and it works very well. However, since I started to [migrate most of my rules from openhab rule system to NodeRED](https://community.openhab.org/t/node-red-as-alternative-rule-engine/29509), I’ve come across a change for the input node that helped me a lot to keep my NodeRED flows clear. I have quite some situations where my original rule consist of a situation where I like to react on a change in sensor state only (“changed from OPEN to CLOSED”). With your Input node I would have to add quite some switch and change blocks to accomplish this. That’s why I’ve [created a new input block](https://github.com/jeroenhendricksen/node-red-contrib-openhab2/pull/1) that helps you omit these required blocks.

I was wondering if you, or anyone else who is using this great plugin would be interested to see this input node added to your plugin. If so, I would like to discuss in what way it would be appropriate and I can of course create a more specific PR that is better suited.

So te be clear. With your input node, if I’d like to monitor for a change, it looks like this:
<img width="786" alt="screen shot 2018-03-02 at 08 25 34" src="https://user-images.githubusercontent.com/32140294/36888171-960fb01c-1df4-11e8-841d-27aefb1ba37b.png">

with my version, it's just the single node:
<img width="216" alt="screen shot 2018-03-02 at 08 28 21" src="https://user-images.githubusercontent.com/32140294/36888156-89f0c528-1df4-11e8-9a55-8bd024e5d1aa.png">

and it's configuration screen currently looks like this:
<img width="832" alt="screen shot 2018-03-02 at 08 36 17" src="https://user-images.githubusercontent.com/32140294/36888234-dc66bba0-1df4-11e8-98a5-3a6319508cb6.png">

Let me know.

**Comment by raufis27** [comment]
Looks useful!

**Comment by fab33** [comment]
It's quite specific. Don't think it's a good idea to put this in this node (Keep it simple). To re-use your example you can create a subflow (or use action node).

**Comment by jeroenhendricksen** [comment]
> It's quite specific. Don't think it's a good idea to put this in this node (Keep it simple). To re-use your example you can create a subflow (or use action node).

That's an alternative pattern I hadn't thought of, thank you for pointing that out. And I agree keeping it simple is very important. However, for my workflows the "advanced" input node still seems to make sense after playing around with subflows, but YMMV of course.

**Comment by pdmangel** [comment]
I always wanted to keep the different nodes as simple as possible and refrained from adding a lot of options which can be wired in easily.
Channel 1 already outputs only changes, so no need for the 'Item Changed' node.
