### ISSUE TITLE
Problem when using with Fibaro FGD-212 (dimmer 2) and scenes

### ISSUE THREAD

**Issue by daballiemo** [pdmangel/node-red-contrib-openhab2#34]
The FGD-212 dimmer will send a scene code "16" if switch 1 is operated with a single click. So the "16" is used to switch the light on if its off (or off if the light is on). When using node-red-contrib-openhab2 (the openhab2-in node) the 2nd and following single clicks are never received, probably because the state does not change.

The description tells:
_- openhab2-in
Listens to state changes of a selected openHAB Item._

It is expected behaviour, but this renders node-red-contrib-openhab2 unusable in combination with Fibaro dimmers and switches.

For now I have created a work around using MQTT and Eventbus.

**Comment by pdmangel** [comment]
Channel 2 of 'openhab2-in' should output all 'raw' events and fulfill your needs.
