### ISSUE TITLE
Not working with Nodered 1.0.1 

### ISSUE THREAD

**Issue by jj74** [pdmangel/node-red-contrib-openhab2#40]
I`ve just updated Nodered to version 1.0.1 (from 0.20.5). One thing which doesn`t work anymore, is using "set_temp" for sending temperature values to a Openhab-DECT Item. On 0.20.5 it worked fine, sending a number payload with a "set_temp" topic to the OH item. The temperature was in- or degreasing. In 1.0.1 you can also send the data to the item, but nothing is changing. It`s also not possible anymore, to toggle the topic between "itemCommand" and "itemUpdate". 
Version 0.25 Screenshots
![version 0 25-a](https://user-images.githubusercontent.com/30443418/66717032-dee65f00-edd4-11e9-8bb0-bffdea28041e.png)
![version 0 25-b](https://user-images.githubusercontent.com/30443418/66717033-e279e600-edd4-11e9-8c63-570d2d809688.png)

Version 1.0.1 Screenshots
![version 1 0 1-a](https://user-images.githubusercontent.com/30443418/66717101-97140780-edd5-11e9-8135-c4db976b13ee.png)
![version 1 0 1-b](https://user-images.githubusercontent.com/30443418/66717104-99766180-edd5-11e9-8e00-c2bfef2ffd8f.png)

Cheers Jesco

**Comment by Christian-Me** [comment]
This is (partly) related to https://github.com/pdmangel/node-red-contrib-openhab2/issues/39

**Comment by pdmangel** [comment]
Fixed in v1.1.6

**Comment by jj74** [comment]
Back in the business! Thanks for fixing it.
