### ISSUE TITLE
openhab2-get very slow with openhab3

### ISSUE THREAD

**Issue by vavo01** [pdmangel/node-red-contrib-openhab2#55]
After migration from openhab2.x to openhab 3.x openhab2-get node needs far more time (~2 seconds) to deliver values.

Used version: lastest 1.1.8

**Comment by TravisWilder** [comment]
Hi I have seen as well that rules in Node-red with OH3 seems slow

**Comment by jschaeke** [comment]
indeed notice the same here: after I updated to OH3 it takes 2 sec for the thing to react when using the NodeRed ui.

**Comment by lampy2** [comment]
Are you using basic auth or the API key?
I saw on the forum also some issues reported with habapp : [link github ](https://github.com/openhab/openhab-core/issues/1899)
Didn't noticed the issue myself yet, responses with rules on motion react almost instant. I am using the authentication token on Rpi4.

**Comment by vavo01** [comment]
You made my day.
I've switched to token authentication and that solved my issue.

**Comment by jschaeke** [comment]
Where do you put the token? I see only username/password fields in the openhab2-controller.

**Comment by lampy2** [comment]
Full token in username, password empty

**Comment by jschaeke** [comment]
Found it:
Created in OPenhab via: http://openhab-ip:8080/createApiToken
Used it in username field in openhab2-controller (empty password).
