### ISSUE TITLE
Case changed of on/off values

### ISSUE THREAD

**Issue by biohazardxxx** [pdmangel/node-red-contrib-openhab2#7]
Hi,
after a few hours of trouble shooting I figured out that the case of vallues gets chaged!
If I set a string Item to "on" it gets set to "ON". Same happens for "off" values.

Saw in the code the conversion is done here: [Line 456](https://github.com/pdmangel/node-red-contrib-openhab2/blob/54cbaf955cb12fb6cc79bbd490b20806c4fb29da/77-openhab2.js#L456)
It should not be the task of the nodes to modify values! This can cause unforseen behaviour in sensetive envorinments.

You can recreate the issue with:
OH item: `String	NodeRedOH2NodesTest	"NodeRed OH2 Nodes test"`
NodeRed test flow: 
`[{"id":"b61224d9.cc1fe8","type":"tab","label":"OH2 Test"},{"id":"c20e21ee.14378","type":"openhab2-in","z":"b61224d9.cc1fe8","name":"Listen: NodeRedOH2NodesTest","controller":"b077e03e.e5f0e","itemname":"NodeRedOH2NodesTest","x":176,"y":330,"wires":[["3cb6803b.d6c9e"],[]]},{"id":"f26eeb96.ea0478","type":"openhab2-out","z":"b61224d9.cc1fe8","name":"SET: NodeRedOH2NodesTest","controller":"b077e03e.e5f0e","itemname":"NodeRedOH2NodesTest","topic":"ItemUpdate","payload":"","x":405,"y":267,"wires":[]},{"id":"37cf3831.5c67d8","type":"inject","z":"b61224d9.cc1fe8","name":"String:off","topic":"","payload":"off","payloadType":"str","repeat":"","crontab":"","once":false,"x":140,"y":268,"wires":[["f26eeb96.ea0478"]]},{"id":"3cb6803b.d6c9e","type":"debug","z":"b61224d9.cc1fe8","name":"","active":true,"console":"false","complete":"false","x":444,"y":322,"wires":[]},{"id":"ff4727d6.79c0c8","type":"inject","z":"b61224d9.cc1fe8","name":"String:on","topic":"","payload":"on","payloadType":"str","repeat":"","crontab":"","once":false,"x":143,"y":221,"wires":[["f26eeb96.ea0478"]]},{"id":"b077e03e.e5f0e","type":"openhab2-controller","z":"","name":"Openhab2_Home","protocol":"http","host":"localhost","port":"8080","path":"","username":"","password":""}]`

**Comment by pdmangel** [comment]
A fix now available in version 1.0.6.
