### ISSUE TITLE
msg.item in Out node

### ISSUE THREAD

**Issue by bebben88** [pdmangel/node-red-contrib-openhab2#9]
I just discovered it's not possible to set an item with something like msg.item to an output node. I want to have one output node for a multifunction voicecommand and I set the outgoing object within the node.

**Comment by joxta** [comment]
I'd really like this ability as well. You already set msg.item in the payload from the openhab2-in node, so please let me set and use it on the openhab2-out node

**Comment by pdmangel** [comment]
This is now available in version 1.0.6.
